## Datasource Configuration
spring.datasource.url = jdbc:mysql://iispiridis.com:3306/iispiri_jkrs7?useSSL=false&serverTimezone=EET
spring.datasource.username = iispiri_root
spring.datasource.password = notpassword

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.dialect=org.hibernate.dialect.MySQL5Dialect


spring.application.name=visit-service